apiVersion: v1
kind: Service
metadata:
  name: trilium
  namespace: trilium
spec:
  selector:
    app: trilium
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP