apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: appdata-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.91.5
  share: /mnt/user/kube
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-appdata-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  volumeMode: Filesystem
  mountOptions:
  - hard
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: stash-appdata-nfs
    volumeAttributes:
      server: 192.168.91.5
      share: /mnt/user/kube/stash
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ''
  mountOptions:
  - hard
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: videos-nfs
    volumeAttributes:
      server: 192.168.91.5
      share: /mnt/user/videos