apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: trilium
spec:
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      hostname: trilium
      volumes:
      - name: appdata-nfs
        persistentVolumeClaim:
          claimName: appdata-nfs
      containers:
      - name: trilium
        image: zadam/trilium:latest
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: appdata-nfs
          mountPath: /data
          subPath: data
        env:
        - name: TRILIUM_DATA_DIR
          value: /data
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"