apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: appdata-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.91.5
  share: /mnt/user/kube
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard