apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      volumes:
      - name: appdata-longhorn
        persistentVolumeClaim:
          claimName: appdata-longhorn
      containers:
      - name: setup
        image: ubuntu
        command:
        - /bin/sh
        args:
        - '-c'
        - |
          echo '
          tunnel: e7ba2cd3-ec45-404f-9792-3363ef546a16
          credentials_file: /etc/cloudflared/e7ba2cd3-ec45-404f-9792-3363ef546a16.json

          ingress:
          - hostname: trilium.coleslab.com
            service: http://192.168.95.130
          - service: http_status:404
          ' > /etc/cloudflared/config.yml & tail -f /dev/null
        volumeMounts:
        - name: appdata-longhorn
          mountPath: /etc/cloudflared
          subPath: config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
      - name: cloudflared
        image: cloudflare/cloudflared:2022.1.2
        args:
        - tunnel
        - --config 
        - /etc/cloudflared/config.yml
        - run
        volumeMounts:
        - name: appdata-longhorn
          mountPath: /etc/cloudflared
          subPath: config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"