apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trilium
  namespace: trilium
spec:
  secretName: trilium-tls
  dnsNames:
  - trilium.services.coleslab.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer