apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudflared-longhorn
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    fsType: xfs
    volumeAttributes:
      diskSelector: ""
      migratable: "false"
      nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: cloudflared
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem