apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-appdata-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  volumeMode: Filesystem
  mountOptions:
  - hard
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: trilium-appdata-nfs
    volumeAttributes:
      server: 192.168.91.5
      share: /mnt/user/kube/trilium